further formatting
remove extra lines (#1074)

Add misc type default blueprint (#1064)

Co-authored-by: Pablo Villanueva-Domingo <pablo.villanueva.domingo@gmail.com>

Fix: wrong initial transform when using request_new_batch_actors (#1068) (#1075)

See: https://github.com/carla-simulator/scenario_runner/pull/1068

Co-authored-by: Daraan <github.blurry@9ox.net>

Update atomic_trigger_conditions.py (#946)

In the StandStill() class, change the EPSILON, 0.001

Implement variable frame rate (#1005)

Replaced class variable frame_rate with an argument provided on the CLI.

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Workflow improvements and code quality passing (#1052)

* CI: Checkout v4 and unit tests name correction

* Small tweaks to ensure Code Quality passes

---------

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Fixed metrics wheel parser (#1076)

Co-authored-by: glopezdiest <glopez@cvc.uab.cat>

[Feature] Blueprint-based spawn_actor function for CarlaDataProvider (#1071)

* blueprint-based spawn_actor function for CDP

* Auto-Option to decide tracking

* Updated changelog

* spawned actors are tracked if they are Vehicle | Walker

* Updated spawn_actor description

---------

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Hotfix: missing AttachmentType in the carla mock module for unittest (#1077)

* blueprint-based spawn_actor function for CDP

* Auto-Option to decide tracking

* Updated changelog

* spawned actors are tracked if they are Vehicle | Walker

* Updated spawn_actor description

* Added missing AttachmentType for carla mock

---------

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Backward compatible upgrade to fix deprecation warnings concerning LooseVersion and pkg_resources for Python3.8+ (#1058)

* upgraded version checking to fix deprecation warnings

Removed usage of pgk_resources and distutils.version.LooseVersion

* < python3.8 backward compatible version checking

* Compacter version checking.

---------

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Replace deprecated python 3.8 code and add missing __init__.py files for proper python module recognition (#1053)

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

add support for scientific notation parsing while running OpenSCENARIO files (#1023)

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Update osc2_scenario_configuration.py (#1040)

Add super.__init__() to class OSC2ScenarioConfiguration to prevent error "AttributeError: 'OSC2ScenarioConfiguration' object has no attribute 'route'" when running scenario_runner.py with --openscenario2 parameter

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Remove version redundancy (#1081)

Update minimum CARLA version to 0.9.14 (#1082)

* Remove version redundancy

* Merge branch 'master' of https://github.com/carla-simulator/scenario_runner

* Update minimum CARLA version

Type-hint comments for CarlaDataProvider (#1066)

* Type-hint comments for CarlaDataProvider

* Suppress Any import warning

* Removed None values, increased type-coverage

Added log agent

[fix]rename compound_symbol.py (#1089)

Fixed a typo in openscenario_parser.py (#1118)

* Fixed a typo

There was a typo in function "get_traffic_light_from_osc_name", which was accessing "CCarlaDataProvider" insted of "CarlaDataProvider".

* Delete the unneeded file

Fix: Remove duplicate clean method calls (#1096)

* [fix]rename compound_symbol.py

* [fix]Remove duplicate clean method calls

* Fix Atomic_behaviors AddActor Func

No return status

Link documentation in README (#1129)

Include 0.9.14 carla release as compatible with scenario runner 0.9.13 (#1130)

* Link documentation in README

* Include 0.9.14 carla release as compatible with scenario runner 0.9.13

* Merge branch 'master' into docs_in_readme

Added a missing element to the blackboard (#1141)

Co-authored-by: glopezdiest <glopez@cvc.uab.cat>

Replaced deprecated is_intersection with is_junction (#1114)

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

CDP request_new_actor new optional argument. (#1113)

spawn_point can be ommited when random_location=True

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Faster information retrieval if actor key is present (#1098)

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Don't depend on distutils (#1121)

distutils are no longer available in Python 3.12. Therefore, we copy
the strtobool function from distutils to our own module. This is in
line with https://peps.python.org/pep-0632/#migration-advice.

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>

Fix dead actor accumulation in CDP (#1091)

* Slightly more informative function

Returns bool if actor was in the pool, else otherwise

* Fix accumulation of dead actors in CDP actor pool

* Dead actor cleaning in CDP._actor_*_maps

---------

Co-authored-by: glopezdiest <58212725+glopezdiest@users.noreply.github.com>